### ISSUE TITLE
Store and Rate Peers

### ISSUE THREAD

**Issue by wanderer** [ethereum/ethereumjs-p2p#1]
Networking should have and rate peers.
To do this we need to
1) take in an instance of leveldb in the Network constructor
2) add the rating Logic to [logic.js](https://github.com/ethereum/ethereumjs-p2p/blob/master/lib/logic.js)

**Comment by Latrasis** [comment]
Do you mean adding a db for Network options? 
https://github.com/ethereum/ethereumjs-p2p#network-options

Such as?...
```js
new Network({db: peerdb});

**Comment by wanderer** [comment]
yep just like that.

**Comment by Latrasis** [comment]
Documentation is a bit off, knownPeers is defined as array but is actually an object housing getPeers()??

**Comment by wanderer** [comment]
Yeah the docs are really old here, sorry will update soon

So internally there is to objects that deal with peers
```  
this._peers = {}; //list of peer connected to
 this._peersList = {}; //list of known but not connected to peers
```

every currently connected peer is stored in `_peers`. After we are connected to the max number of peers (`this.maxPeers`)  each new peer we learn about is put into `_peerList`. When a peer disconnects we replace it with a peer from the `_peerList`

**Comment by Latrasis** [comment]
I can see that, but then what about the self.getPeers() that is being used in source?

**Comment by wanderer** [comment]
yep that is different. The send a `getPeers` packet to that peer.

**Comment by Latrasis** [comment]
Yo, i've been in a jiffy lately -  still not sure at what event i should put rep management in logic.

**Comment by wanderer** [comment]
No Problem! I really appreciate the help. So first of all you should load peers from the db and try to connect to them in the [listen function](https://github.com/ethereum/ethereumjs-p2p/blob/master/lib/index.js#L154) So right now you only rate peers based on if we can connect to them or not.  We don't need to use any events here. Forget what I said about putting stuff in logic.js, thats not a good idea. Instead just put  the `evelPeer` function in its own file `rating.js` or something like that. The reason for this is that in the future we may develop more complicated rating functions and it will make it easier to work on if it in its a module.

**Comment by Latrasis** [comment]
Ok so i added rating.js at #2 

Next up is tests

**Comment by Latrasis** [comment]
Looks like Storing and Rating is moved off to ethereum-dht then.
